In [4]:
import prediction as pr

In [12]:
upload = pr.folder
print(upload)

./transactions-ser

In [13]:
# Lire les fichier csv et les fusionner en 1 seul fichier
df = pr.read_and_merge(upload)
df

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
0,2022-359835,2022-03-18,1,Vente,115000.0,9001.0,None,IMMEUBLE ATLANTIDE,A651,76800,...,110.0,6.0,None,None,None,None,NaN,1.071577,49.393501,000BS
1,2022-359835,2022-03-18,1,Vente,115000.0,9001.0,None,IMMEUBLE ATLANTIDE,A651,76800,...,NaN,0.0,None,None,None,None,NaN,1.071577,49.393501,000BS
2,2022-359041,2022-01-18,1,Vente,181300.0,4.0,None,ALL DU CLOS MAJORELLE,0517,76800,...,83.0,4.0,S,sols,None,None,97.0,1.068890,49.391763,000BS
3,2022-359041,2022-01-18,1,Vente,181300.0,4.0,None,ALL DU CLOS MAJORELLE,0517,76800,...,NaN,0.0,S,sols,None,None,12.0,1.068805,49.391922,000BS
4,2022-359041,2022-01-18,1,Vente,181300.0,1.0,None,ALL DU CLOS MAJORELLE,0517,76800,...,NaN,0.0,S,sols,None,None,13.0,1.068709,49.392102,000BS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,2017-545059,2017-10-25,1,Vente,170000.0,171.0,None,RUE DE PARIS,1840,76800,...,140.0,6.0,S,sols,None,None,727.0,1.106699,49.388487,000BD
90,2017-544418,2017-09-26,1,Vente,174000.0,19.0,None,RUE DE LA REPUBLIQUE,2180,76800,...,57.0,4.0,S,sols,None,None,448.0,1.105192,49.389305,000BD
91,2017-544418,2017-09-26,1,Vente,174000.0,15.0,None,RUE DE LA REPUBLIQUE,2180,76800,...,NaN,NaN,S,sols,None,None,220.0,1.104911,49.389243,000BD
92,2017-543711,2017-08-07,1,Vente,250000.0,145.0,None,RUE DE PARIS,1840,76800,...,153.0,5.0,J,jardins,POTAG,Jardin potager,685.0,1.106324,49.389849,000BD
93,2017-543711,2017-08-07,1,Vente,250000.0,145.0,None,RUE DE PARIS,1840,76800,...,153.0,5.0,S,sols,None,None,500.0,1.106324,49.389849,000BD

In [14]:
# Nettoyage du DataFrame
df = pr.data_cleaning(df)
df

,valeur_fonciere,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude,section_prefixe,surface
16,73000.0,1,2,Appartement,100.0,5.0,0.0,1.071577,49.393501,000BS,94.23
62,96500.0,1,2,Appartement,64.0,4.0,0.0,1.060400,49.392643,000BS,63.43
71,200000.0,0,1,Maison,86.0,4.0,417.0,1.063211,49.392964,000BS,86.00
110,112000.0,0,1,Maison,63.0,4.0,263.0,1.061100,49.394313,000BS,63.00
117,69000.0,1,2,Appartement,31.0,1.0,0.0,1.071577,49.393501,000BS,30.44
...,...,...,...,...,...,...,...,...,...,...,...
33,211550.0,0,1,Maison,130.0,6.0,53.0,1.105048,49.389845,000BD,130.00
43,93000.0,0,1,Maison,83.0,4.0,133.0,1.105306,49.388171,000BD,83.00
55,90000.0,0,1,Maison,58.0,3.0,58.0,1.105265,49.387870,000BD,58.00
71,91000.0,0,1,Maison,54.0,3.0,43.0,1.105094,49.387773,000BD,54.00
73,211000.0,0,1,Maison,125.0,4.0,259.0,1.104295,49.387879,000BD,125.00

In [21]:
# Exemple de variables
surface = 94.23
type_local = 2 #1 pour maison, 2 pour appartement
surface_terrain = 100
nb_pieces = 5

In [22]:
# Foction de prédiction
pr.predict(surface, type_local, surface_terrain, nb_pieces)

/home/hiba/.local/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

84034.31